build:
	docker build -t hemgajjarbypt/my_python_sentiment_image:latest .

push:
	docker push hemgajjarbypt/my_python_sentiment_image:latest

run:
	docker compose -f compose.yml -p my_python_sentiment_project up -d